spring.application.name=football-tournament-api

spring.datasource.url=jdbc:postgresql://localhost:5432/football-tournament-api
spring.datasource.username=postgres
spring.datasource.password=Orxan1999.
spring.jpa.hibernate.ddl-auto=validate