spring.application.name=football-tournament-api

spring.datasource.url=jdbc:postgresql://db:5432/football-tournament-api
spring.datasource.username=postgres
spring.datasource.password=Orxan1999..
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


application.security.jwt.secret-key=X5SFi6Na5G3SW0aCpo60SyoFM721lVFfR4lQCBJtOo3
application.security.jwt.expiration=6000000
application.security.jwt.refresh-token.expiration=604800000