CREATE TABLE teams (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             name VARCHAR(100) NOT NULL unique ,
                             is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                             deleted_at TIMESTAMP,
                            created_at TIMESTAMP,
                            updated_at TIMESTAMP,
                             CONSTRAINT uk_teams_name UNIQUE (name)
);


CREATE TABLE players (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(100) NOT NULL unique ,
                       is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                        team_id BIGINT,
                       deleted_at TIMESTAMP,
                       created_at TIMESTAMP,
                       updated_at TIMESTAMP,
                       CONSTRAINT uk_players_name UNIQUE (name),
    CONSTRAINT fk_players_team foreign key (team_id) references teams(id)
);

create index idx_players_team_id on teams(id)