CREATE TABLE head_coaches (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(100) NOT NULL ,
                         is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                         deleted_at TIMESTAMP,
                         created_at TIMESTAMP,
                         updated_at TIMESTAMP
);



CREATE UNIQUE INDEX idx_head_coaches_name_active
    ON players (name)
    WHERE is_deleted = false;


alter table teams
add column head_coach_id BIGINT;

ALTER TABLE teams
    ADD CONSTRAINT fk_teams_head_coach
        FOREIGN KEY (head_coach_id)
            REFERENCES head_coaches(id)
            ON DELETE SET NULL;