CREATE TABLE tournament_teams (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              team_id BIGINT,
                              tournament_id BIGINT,
                              is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                              deleted_at TIMESTAMP,
                              created_at TIMESTAMP,
                              updated_at TIMESTAMP
);

CREATE TABLE tournaments (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name VARCHAR(100) NOT NULL,
                                  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
                                  deleted_at TIMESTAMP,
                                  created_at TIMESTAMP,
                                  updated_at TIMESTAMP
);

CREATE UNIQUE INDEX idx_tournaments_name_active
    ON tournaments (name)
    WHERE is_deleted = false;