CREATE TABLE matches (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             home_team_id BIGINT,
                             away_team_id BIGINT,
                             home_team_score BIGINT,
                             away_team_score BIGINT,
                             tournament_id BIGINT
);