CREATE TABLE standings
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id         BIGINT,
    tournament_id   BIGINT,
    played          INT              default 0,
    won             INT              DEFAULT 0,
    drawn           INT              DEFAULT 0,
    lost            INT              DEFAULT 0,
    goals_for       INT              DEFAULT 0,
    goals_against   INT              DEFAULT 0,
    goal_difference INT              DEFAULT 0,
    points          INT              DEFAULT 0,
    is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMP,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    constraint fk_standing_tournament foreign key (tournament_id) references tournaments(id),
    constraint fk_standing_team foreign key (team_id) references teams(id),
    constraint uk_tournament_team unique (tournament_id,team_id)

);

CREATE INDEX idx_standings_tournament ON standings(tournament_id);

